# Generated by Django 5.2 on 2025-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoffer',
            name='expiration_date',
            field=models.DateField(default='2025-06-01'),
            preserve_default=False,
        ),
    ]
