# Generated by Django 5.2 on 2025-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_purchaseoffer_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoffer',
            name='contingent_message',
            field=models.TextField(blank=True),
        ),
    ]
