# Generated by Django 5.2 on 2025-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruser',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_covers/'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_logos/'),
        ),
    ]
