# Generated by Django 5.2.1 on 2025-05-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
