# Generated by Django 5.2 on 2025-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
