# Generated by Django 5.2 on 2025-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPhoto',
            new_name='PropertyPhoto',
        ),
    ]
