# Generated by Django 5.2 on 2025-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_rooms_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='image',
            field=models.ImageField(upload_to='property_photos/'),
        ),
    ]
