# Generated by Django 5.2 on 2025-05-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_userphoto_propertyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.property'),
        ),
    ]
