# Generated by Django 5.2 on 2025-05-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertyphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
