# Generated by Django 5.2 on 2025-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertyphoto_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.IntegerField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='listing_date',
            field=models.DateField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.IntegerField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='square_meters',
            field=models.IntegerField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.BooleanField(default='temp'),
            preserve_default=False,
        ),
    ]
