# Generated by Django 5.2 on 2025-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
