# Generated by Django 5.2 on 2025-05-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_favorite_delete_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
